### 당신의 이웃에 따라서 당신을 위치 판단합니다.

### 설치합니다.

In [1]:
import numpy as np

In [2]:
pip install sklearn

Note: you may need to restart the kernel to use updated packages.


### 패키지를 가져옵니다.

In [3]:
from sklearn.neighbors import KNeighborsClassifier # 이웃에 따라 분류를 수행합니다.

In [4]:
from sklearn import datasets # 학습을 위해 제공되는 데이터를 로드합니다

### 데이터를 로드합니다.

In [4]:
#X는 특성 데이터이고, y는 목표 값입니다. 
#X ---> y로 특성을 기반으로 분류를 수행합니다. 
#남자, 여자, 특성을 기반으로 분류합니다
#대부분의 경우, 특성을 기반으로 분류합니다.
X,y = datasets.load_iris(return_X_y=True)# 붓꽃 데이터는 세 가지 범주로 분류됩니다. 꽃받침과 꽃잎의 길이와 너비입니다.
display(X,y)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
# 데이터 차원
# X는 2차원이어야 합니다.
# y에는 제한이 없습니다.
display(X.shape,y.shape)

(150, 4)

(150,)

### 데이터 분할

In [6]:
from sklearn.model_selection import train_test_split # 데이터 분할

In [8]:
# 훈련 데이터를 사용하여 알고리즘에게 규칙을 학습시킵니다.
# 테스트 데이터로 규칙을 적용합니다.
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2) # 30개 테스트 데이터
display(X_train.shape,X_test.shape)

(120, 4)

(30, 4)

### 알고리즘 모델링

In [9]:
knn = KNeighborsClassifier(n_neighbors=5) # 5명의 이웃이 결정하여 어떤 범주에 속하는지 투표합니다.

# 데이터의 규칙은 범주를 결정합니다.
knn.fit(X_train,y_train) # 훈련: 모델링, 규칙 요약

KNeighborsClassifier()

### 알고리즘 적용 [실제 사용]

In [10]:
knn.predict(X_test) # 테스트 데이터는 보존되며, knn 알고리즘은 이전에 본 적 없는 새로운 데이터에 적용됩니다.

array([2, 2, 2, 0, 1, 2, 0, 1, 0, 2, 2, 0, 2, 1, 2, 0, 1, 0, 2, 2, 1, 0,
       0, 1, 2, 2, 1, 0, 0, 2])

In [11]:
y_test

array([2, 2, 2, 0, 2, 2, 0, 1, 0, 2, 1, 0, 1, 1, 2, 0, 1, 0, 2, 2, 1, 0,
       0, 1, 2, 2, 1, 0, 0, 2])

### 정확도

In [13]:
# 90%
(y_test == knn.predict(X_test)).mean()

0.9

In [14]:
knn.score(X_test,y_test)

0.9