### 자료형 (jaryohyeong)

In [ ]:
import numpy as np

arr1 = np.array([1,2,3,127,128],dtype=np.int8)
#비트 수가 더 크면 차지하는 메모리도 더 큽니다. (biteu su-ga deo keu-keu-myeon chajineun memori-do deo keurimnida.)
display(arr1,2**8)

arr2 = np.array([1,2,-5,8,255,256],dtype=np.int8)
display(arr2）

In [2]:
# 위 코드에서 -128이 출력됩니다. 이는 int 자료형의 범위를 초과하였기 때문입니다.
# 마찬가지로, 255와 256을 출력하면, -1과 0으로 변환됩니다.
# 이러한 작은 지식, 왜 255가 -1로, 256이 0으로 변환되는지에 대한 이유입니다.

8位整数可以表示的值范围是-128到+127。当数组中的元素值超出这个范围时，会发生整数溢出，即最高有效位会被丢弃，只保留最低的8位（1字节），这可能导致表示的值发生变化。

在数组中，255的二进制表示为11111111，它在8位整数中的表示方式是-1，因为最高有效位是1，意味着这是一个负数。类似地，256的二进制表示为100000000，但由于它不能用8位整数表示，因此会发生溢出，并保留了最低的8位，即00000000，这被解释为0。

In [3]:
arr3 = np.array([1,2,-5,8,255,256],dtype=np.uint8)
display(arr3)

# 0-255

array([  1,   2, 251,   8, 255,   0], dtype=uint8)

In [4]:
arr1 = np.random.randint(0,150,size = (10000,3),dtype=np.int16)
arr2 = arr1.astype(np.int64)
display(arr1,arr2)
#숫자가 출력되는 것은 같지만, 컴퓨터에서 사용하는 메모리 공간은 다를 수 있습니다.


array([[134,  57,  43],
       [  4, 133,  65],
       [134, 124,  13],
       ...,
       [ 54,   6,  69],
       [ 29,  49,  25],
       [ 80,  92,  43]], dtype=int16)

array([[134,  57,  43],
       [  4, 133,  65],
       [134, 124,  13],
       ...,
       [ 54,   6,  69],
       [ 29,  49,  25],
       [ 80,  92,  43]])

In [5]:
arr3 = np.random.randn(100)
#각 요소는 표준 정규 분포(평균 0, 표준 편차 1)에서 독립적으로 무작위로 추출됩니다. 

display(arr3,arr3.dtype)
arr4 = arr3.astype(np.float16)
display(arr4,arr4.dtype)
#아래 그림에서 확인할 수 있듯이, 16비트 숫자는 더욱 정확합니다. 

array([-0.06507675,  0.14297543,  1.47847468,  0.16963733, -0.14731854,
        0.32518171, -2.27218738, -0.3730286 ,  0.56283709,  1.33834177,
       -0.09573432, -0.1772638 ,  0.62559524,  0.02024542, -0.52312678,
        2.02398136, -1.19782248, -0.51088909, -1.5591118 ,  0.91149772,
       -0.71037719,  0.27554176, -0.89158023, -1.84307923,  0.24986975,
        1.10170159, -0.09756599,  0.43074352,  0.86079085,  1.18713547,
       -0.46008304,  1.76717227, -1.1708877 , -0.79148839,  1.9597641 ,
       -2.52052794,  0.7757333 ,  2.49295291, -1.36352495, -0.23308048,
        0.29834195,  0.68487592,  0.37914906, -1.11133985, -1.343791  ,
       -0.17531721, -1.29810275, -1.76659431, -0.7204521 , -0.06137495,
        1.93332009,  1.69966383, -0.42764334,  0.60431855,  0.84627167,
       -2.42729504, -0.3007764 , -0.02344746,  1.08194799, -0.69629646,
        0.06835717, -0.44395405, -0.77504631, -0.95837504, -0.68006446,
        0.12533349,  0.03047407, -0.78619167, -0.92167377, -1.72

dtype('float64')

array([-0.06506,  0.143  ,  1.479  ,  0.1697 , -0.1473 ,  0.3252 ,
       -2.271  , -0.373  ,  0.563  ,  1.338  , -0.09576, -0.1772 ,
        0.6255 ,  0.02025, -0.523  ,  2.023  , -1.198  , -0.5107 ,
       -1.56   ,  0.9116 , -0.7104 ,  0.2756 , -0.8916 , -1.843  ,
        0.2499 ,  1.102  , -0.0976 ,  0.4307 ,  0.861  ,  1.1875 ,
       -0.4602 ,  1.768  , -1.171  , -0.7915 ,  1.96   , -2.521  ,
        0.776  ,  2.492  , -1.363  , -0.233  ,  0.2983 ,  0.685  ,
        0.3792 , -1.111  , -1.344  , -0.1753 , -1.298  , -1.767  ,
       -0.72   , -0.06137,  1.934  ,  1.699  , -0.4277 ,  0.6045 ,
        0.846  , -2.428  , -0.3008 , -0.02345,  1.082  , -0.6963 ,
        0.06836, -0.4438 , -0.775  , -0.9585 , -0.68   ,  0.1254 ,
        0.03047, -0.786  , -0.922  , -1.721  , -1.714  , -1.193  ,
       -0.1282 ,  0.809  , -0.925  ,  0.798  ,  1.388  ,  0.587  ,
        0.2817 , -1.681  ,  0.0832 ,  0.4548 , -2.117  , -1.888  ,
       -0.4707 , -0.2083 , -1.354  , -1.028  , -0.3542 , -0.78

dtype('float16')

### 배열 연산

#### 일반적인 연산

In [6]:
arr1 = np.random.randint(0,10,size = (3,5))
display(arr1,arr1+1,arr1-5)

array([[3, 2, 7, 4, 2],
       [5, 9, 0, 3, 3],
       [3, 9, 0, 8, 2]])

array([[ 4,  3,  8,  5,  3],
       [ 6, 10,  1,  4,  4],
       [ 4, 10,  1,  9,  3]])

array([[-2, -3,  2, -1, -3],
       [ 0,  4, -5, -2, -2],
       [-2,  4, -5,  3, -3]])

In [7]:

display(arr1**2,(arr1**0.5).dtype) # dtype


array([[ 9,  4, 49, 16,  4],
       [25, 81,  0,  9,  9],
       [ 9, 81,  0, 64,  4]])

dtype('float64')

In [8]:
display(arr1/3)

array([[1.        , 0.66666667, 2.33333333, 1.33333333, 0.66666667],
       [1.66666667, 3.        , 0.        , 1.        , 1.        ],
       [1.        , 3.        , 0.        , 2.66666667, 0.66666667]])

In [9]:
# 3.   float,64비트의 뜻입니다

In [10]:
display(arr1,arr1//2,(arr1%3).dtype)

array([[3, 2, 7, 4, 2],
       [5, 9, 0, 3, 3],
       [3, 9, 0, 8, 2]])

array([[1, 1, 3, 2, 1],
       [2, 4, 0, 1, 1],
       [1, 4, 0, 4, 1]])

dtype('int64')

#### 로직연산

In [11]:
display(arr1,arr1 == 3,arr1<5)

array([[3, 2, 7, 4, 2],
       [5, 9, 0, 3, 3],
       [3, 9, 0, 8, 2]])

array([[ True, False, False, False, False],
       [False, False, False,  True,  True],
       [ True, False, False, False, False]])

array([[ True,  True, False,  True,  True],
       [False, False,  True,  True,  True],
       [ True, False,  True, False,  True]])

In [12]:
display((arr1 > 2) & (arr1<=4)) 

array([[ True, False, False,  True, False],
       [False, False, False,  True,  True],
       [ True, False, False, False, False]])

In [13]:
display(~(arr1 >2))

array([[False,  True, False, False,  True],
       [False, False,  True, False, False],
       [False, False,  True, False,  True]])

In [14]:
display((arr1 == 1)|(arr1 == 9))

array([[False, False, False, False, False],
       [False,  True, False, False, False],
       [False,  True, False, False, False]])

#### *=，+=，/=，-=

In [15]:
arr1

array([[3, 2, 7, 4, 2],
       [5, 9, 0, 3, 3],
       [3, 9, 0, 8, 2]])

In [16]:
arr1 -= 10
arr1
# 모두 데이터 -10

array([[ -7,  -8,  -3,  -6,  -8],
       [ -5,  -1, -10,  -7,  -7],
       [ -7,  -1, -10,  -2,  -8]])

In [17]:
arr1 +=20
arr1
#모두 데이터 +20

array([[13, 12, 17, 14, 12],
       [15, 19, 10, 13, 13],
       [13, 19, 10, 18, 12]])

In [18]:
arr1 *=2
arr1

array([[26, 24, 34, 28, 24],
       [30, 38, 20, 26, 26],
       [26, 38, 20, 36, 24]])

In [19]:
# 원래 자료형 int
# 자료형을 변환하면 오류가 발생하지 않습니다
arr2 =arr1.astype(np.float32)
display(arr1,arr2)
arr2 /=4
arr2

array([[26, 24, 34, 28, 24],
       [30, 38, 20, 26, 26],
       [26, 38, 20, 36, 24]])

array([[26., 24., 34., 28., 24.],
       [30., 38., 20., 26., 26.],
       [26., 38., 20., 36., 24.]], dtype=float32)

array([[6.5, 6. , 8.5, 7. , 6. ],
       [7.5, 9.5, 5. , 6.5, 6.5],
       [6.5, 9.5, 5. , 9. , 6. ]], dtype=float32)

#### 数组和数组运算

In [20]:
arr1
arr3 = np.array([1,2,3,4,5])
display(arr1,arr3)

array([[26, 24, 34, 28, 24],
       [30, 38, 20, 26, 26],
       [26, 38, 20, 36, 24]])

array([1, 2, 3, 4, 5])

In [21]:
arr1 + arr3 #广播机制

array([[27, 26, 37, 32, 29],
       [31, 40, 23, 30, 31],
       [27, 40, 23, 40, 29]])

### 复制和视图

#### 完全没有复制

In [22]:
a= np.random.randint(0,100,size = [4,5])
b=a
display(b)
print(a is b)

b[0,0]= 7630
display(a,b)

array([[29, 79, 94, 82, 84],
       [70, 93, 18, 44, 24],
       [75, 67, 75, 46,  3],
       [21, 60, 30, 18, 96]])

True


array([[7630,   79,   94,   82,   84],
       [  70,   93,   18,   44,   24],
       [  75,   67,   75,   46,    3],
       [  21,   60,   30,   18,   96]])

array([[7630,   79,   94,   82,   84],
       [  70,   93,   18,   44,   24],
       [  75,   67,   75,   46,    3],
       [  21,   60,   30,   18,   96]])

In [23]:
import numpy as np

#### 深拷贝

In [24]:
a = np.random.randint(0,100, size = (4,5))
display(a)
b = a.copy() #两者就不同了
print(b is a)# False

#b的内存指向，是否相同
print(b.base is a)

#变量数据，是否属于它自己
#b.flags 获得变量的自身信息,owndata:判断数据是否是自己的
# 属于True 不属于 False
print(b.flags.owndata)

print(a.flags.owndata)
b[0,0] = 1024
display(a,b)

array([[31, 62, 24, 66, 63],
       [73, 98, 64, 64, 51],
       [81, 81, 45, 57, 16],
       [29, 49, 10, 15, 91]])

False
False
True
True


array([[31, 62, 24, 66, 63],
       [73, 98, 64, 64, 51],
       [81, 81, 45, 57, 16],
       [29, 49, 10, 15, 91]])

array([[1024,   62,   24,   66,   63],
       [  73,   98,   64,   64,   51],
       [  81,   81,   45,   57,   16],
       [  29,   49,   10,   15,   91]])

#### 浅拷贝

In [25]:
a = np.random.randint(0,100, size = (4,5))
display(a)
b = a.view() #使用a中的数据创建一个新数组对象
print(a is b)# 返回False,a和b是两个不同名字对应同一个内存对象

#b的内存指向，是否相同
print(b.base is a)

#变量数据，是否属于它自己
#b.flags 获得变量的自身信息,owndata:判断数据是否是自己的
# 属于True 不属于 False
print(b.flags.owndata)

print(a.flags.owndata)
b[0,0] = 1024
display(a,b)

array([[23, 68, 36, 90, 78],
       [38,  2, 61, 15, 62],
       [99, 10, 48, 25, 42],
       [71, 55, 63, 25, 29]])

False
True
False
True


array([[1024,   68,   36,   90,   78],
       [  38,    2,   61,   15,   62],
       [  99,   10,   48,   25,   42],
       [  71,   55,   63,   25,   29]])

array([[1024,   68,   36,   90,   78],
       [  38,    2,   61,   15,   62],
       [  99,   10,   48,   25,   42],
       [  71,   55,   63,   25,   29]])

### 索引，切片

#### 深拷贝应用

In [26]:
import numpy as np

In [27]:
import gc #垃圾回收
a = np.arange(1e8)
display(a)
b = a[::1000000].copy()#每100万个数据中提取一个数据
del a #不需要a，删除占大内存的a
gc.collect()
display(b,b.shape)
#由于每100万个数据中提取一个数据，所以打印出来就是
#0-1百万-2百万-3百万，一次一百万的向后涨

array([0.0000000e+00, 1.0000000e+00, 2.0000000e+00, ..., 9.9999997e+07,
       9.9999998e+07, 9.9999999e+07])

array([       0.,  1000000.,  2000000.,  3000000.,  4000000.,  5000000.,
        6000000.,  7000000.,  8000000.,  9000000., 10000000., 11000000.,
       12000000., 13000000., 14000000., 15000000., 16000000., 17000000.,
       18000000., 19000000., 20000000., 21000000., 22000000., 23000000.,
       24000000., 25000000., 26000000., 27000000., 28000000., 29000000.,
       30000000., 31000000., 32000000., 33000000., 34000000., 35000000.,
       36000000., 37000000., 38000000., 39000000., 40000000., 41000000.,
       42000000., 43000000., 44000000., 45000000., 46000000., 47000000.,
       48000000., 49000000., 50000000., 51000000., 52000000., 53000000.,
       54000000., 55000000., 56000000., 57000000., 58000000., 59000000.,
       60000000., 61000000., 62000000., 63000000., 64000000., 65000000.,
       66000000., 67000000., 68000000., 69000000., 70000000., 71000000.,
       72000000., 73000000., 74000000., 75000000., 76000000., 77000000.,
       78000000., 79000000., 80000000., 81000000., 

(100,)

#### 基本的索引和切片

In [28]:
arr2 = np.random.randint(0,100,size = (5,4))
display(arr2)
#索引都是从0开始的。

array([[89, 65, 87, 59],
       [83,  8, 66,  0],
       [20, 10, 60, 11],
       [ 6, 93, 54, 95],
       [57, 51,  9, 34]])

In [29]:
arr2[0,0]

89

In [30]:
arr2[2,2]

60

In [31]:
# 如果倒着数的话，会从 87的 -1 开始
arr2[-1,-1]

34

In [32]:
# 取两个数字
arr2[[0,2],[1,3]]
# arr2 [0,[0,1]]
# 直接写0也可以的

array([65, 11])

切片

In [33]:
# 左闭右开
display(arr2,arr2[1:3])

array([[89, 65, 87, 59],
       [83,  8, 66,  0],
       [20, 10, 60, 11],
       [ 6, 93, 54, 95],
       [57, 51,  9, 34]])

array([[83,  8, 66,  0],
       [20, 10, 60, 11]])

In [34]:
arr2[2:4,0:2]


array([[20, 10],
       [ 6, 93]])

In [35]:
arr2[2:4,[0,3]]
#和上面不同，这个里面还有一个[]号，代表的是列
# 

array([[20, 11],
       [ 6, 95]])

In [36]:
display(arr2,arr2[::2],arr2[1::2])
#::2表示 两个中取一个

array([[89, 65, 87, 59],
       [83,  8, 66,  0],
       [20, 10, 60, 11],
       [ 6, 93, 54, 95],
       [57, 51,  9, 34]])

array([[89, 65, 87, 59],
       [20, 10, 60, 11],
       [57, 51,  9, 34]])

array([[83,  8, 66,  0],
       [ 6, 93, 54, 95]])

In [37]:
arr2[[0,3]][:,[0,3]]
#中间 ：分号如果不写东西的话就默认取所有！

array([[89, 59],
       [ 6, 95]])

In [38]:
arr2[::2,1::2]
#奇数行，偶数列
#在这里面是 从索引1开始，每两个中取一个。

array([[65, 59],
       [10, 11],
       [51, 34]])

#### 花式索引和索引技巧

In [39]:
display(arr2,arr2[[0,1,0,2,0]])
#可以重复多次

array([[89, 65, 87, 59],
       [83,  8, 66,  0],
       [20, 10, 60, 11],
       [ 6, 93, 54, 95],
       [57, 51,  9, 34]])

array([[89, 65, 87, 59],
       [83,  8, 66,  0],
       [89, 65, 87, 59],
       [20, 10, 60, 11],
       [89, 65, 87, 59]])

In [40]:
arr2

array([[89, 65, 87, 59],
       [83,  8, 66,  0],
       [20, 10, 60, 11],
       [ 6, 93, 54, 95],
       [57, 51,  9, 34]])

In [41]:
# 取第四行
arr2[[0,3,3,3]][:,[1,3,3]]
#这样输入的话，相当于第四行取了三次
#根据基数行，偶数列

array([[65, 59, 59],
       [93, 95, 95],
       [93, 95, 95],
       [93, 95, 95]])

In [42]:
arr2[np.ix_([1,3,3,3],[1,3,3])]
# np.ix 可以进行一个交叉
#从一维变成了二维
#arr[[0,3,3,3],[1,3,3]]
#如果逗号前面给行，逗号后面给列，这样直接报错

array([[ 8,  0,  0],
       [93, 95, 95],
       [93, 95, 95],
       [93, 95, 95]])

boolean 类型的索引

In [43]:
arr1 = np.random.randint(0,100, size = (59))
arr1

array([99, 28, 31, 94, 28, 33, 19, 65, 74, 91, 40, 88, 14, 61, 54, 20, 52,
       60, 83, 32,  8,  8, 95, 23, 55, 51, 49, 23, 37, 75, 86, 95, 19, 13,
       49, 79, 76, 78, 43, 34, 48, 19, 49,  5,  7, 92, 55,  4, 15, 63, 72,
       86, 54, 55, 69, 90, 74, 36, 82])

In [45]:
cond = arr1 >80
cond

array([ True, False, False,  True, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
        True, False, False, False,  True, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False,  True, False, False,  True])

In [46]:
arr1[cond]

array([99, 94, 91, 88, 83, 95, 86, 95, 92, 86, 90, 82])

In [47]:
cond2 = (arr1 <10)|(arr1 >90)
cond2

array([ True, False, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True, False,  True, False, False, False, False, False, False,
       False, False, False, False, False])

In [48]:
arr1[cond]

array([99, 94, 91, 88, 83, 95, 86, 95, 92, 86, 90, 82])

In [49]:
arr3 = np.random.randint(0,100,size = (4,5,3,))
arr3

array([[[55, 20, 42],
        [ 5, 72, 57],
        [72, 57,  6],
        [66, 46, 68],
        [39, 30, 48]],

       [[67, 51, 22],
        [73, 52, 53],
        [44, 18, 62],
        [78,  4, 88],
        [45, 41, 94]],

       [[77,  4, 93],
        [10, 38, 94],
        [19, 39, 96],
        [ 3, 39, 55],
        [89,  7,  6]],

       [[86,  4, 47],
        [58, 23,  6],
        [47, 96, 68],
        [48, 67, 94],
        [73, 55, 55]]])

In [50]:
arr3[[-1,2],[2,1]]
#取出最后一个数字

array([[47, 96, 68],
       [10, 38, 94]])

In [51]:
arr3.shape
#知道几维

(4, 5, 3)

In [52]:
#如果打算把偶数行取出来
arr3[::2,1::2,::2]

array([[[ 5, 57],
        [66, 68]],

       [[10, 94],
        [ 3, 55]]])

In [53]:
display(arr1,arr1[::-1])# 进行了颠倒

array([99, 28, 31, 94, 28, 33, 19, 65, 74, 91, 40, 88, 14, 61, 54, 20, 52,
       60, 83, 32,  8,  8, 95, 23, 55, 51, 49, 23, 37, 75, 86, 95, 19, 13,
       49, 79, 76, 78, 43, 34, 48, 19, 49,  5,  7, 92, 55,  4, 15, 63, 72,
       86, 54, 55, 69, 90, 74, 36, 82])

array([82, 36, 74, 90, 69, 55, 54, 86, 72, 63, 15,  4, 55, 92,  7,  5, 49,
       19, 48, 34, 43, 78, 76, 79, 49, 13, 19, 95, 86, 75, 37, 23, 49, 51,
       55, 23, 95,  8,  8, 32, 83, 60, 52, 20, 54, 61, 14, 88, 40, 91, 74,
       65, 19, 33, 28, 94, 31, 28, 99])

In [54]:
display(arr1,arr1[::-1],arr1[::-3])
#每三个当中取一个，倒着取

array([99, 28, 31, 94, 28, 33, 19, 65, 74, 91, 40, 88, 14, 61, 54, 20, 52,
       60, 83, 32,  8,  8, 95, 23, 55, 51, 49, 23, 37, 75, 86, 95, 19, 13,
       49, 79, 76, 78, 43, 34, 48, 19, 49,  5,  7, 92, 55,  4, 15, 63, 72,
       86, 54, 55, 69, 90, 74, 36, 82])

array([82, 36, 74, 90, 69, 55, 54, 86, 72, 63, 15,  4, 55, 92,  7,  5, 49,
       19, 48, 34, 43, 78, 76, 79, 49, 13, 19, 95, 86, 75, 37, 23, 49, 51,
       55, 23, 95,  8,  8, 32, 83, 60, 52, 20, 54, 61, 14, 88, 40, 91, 74,
       65, 19, 33, 28, 94, 31, 28, 99])

array([82, 90, 54, 63, 55,  5, 48, 78, 49, 95, 37, 51, 95, 32, 52, 61, 40,
       65, 28, 28])

### 形状操作

#### reshape

In [55]:
arr = np.random.randint(0,100,size = (3,6))
arr

array([[73, 97, 71, 86, 44, 54],
       [43,  4, 89, 31, 46, 16],
       [74, 99, 35, 53, 76, 40]])

In [56]:
arr.reshape(9,2)
#但是9行3列就不行，因为数据量不够
#(9,3)是不行的

array([[73, 97],
       [71, 86],
       [44, 54],
       [43,  4],
       [89, 31],
       [46, 16],
       [74, 99],
       [35, 53],
       [76, 40]])

#### 转置

In [57]:
# 行变列，列变行
arr

array([[73, 97, 71, 86, 44, 54],
       [43,  4, 89, 31, 46, 16],
       [74, 99, 35, 53, 76, 40]])

In [58]:
arr.T

array([[73, 43, 74],
       [97,  4, 99],
       [71, 89, 35],
       [86, 31, 53],
       [44, 46, 76],
       [54, 16, 40]])

In [59]:
arr.reshape(6,3)
#和上面转置不一样

array([[73, 97, 71],
       [86, 44, 54],
       [43,  4, 89],
       [31, 46, 16],
       [74, 99, 35],
       [53, 76, 40]])

In [60]:
arr3

array([[[55, 20, 42],
        [ 5, 72, 57],
        [72, 57,  6],
        [66, 46, 68],
        [39, 30, 48]],

       [[67, 51, 22],
        [73, 52, 53],
        [44, 18, 62],
        [78,  4, 88],
        [45, 41, 94]],

       [[77,  4, 93],
        [10, 38, 94],
        [19, 39, 96],
        [ 3, 39, 55],
        [89,  7,  6]],

       [[86,  4, 47],
        [58, 23,  6],
        [47, 96, 68],
        [48, 67, 94],
        [73, 55, 55]]])

In [61]:
arr3.T
# 默认就是第一维和最后一维进行的转置

array([[[55, 67, 77, 86],
        [ 5, 73, 10, 58],
        [72, 44, 19, 47],
        [66, 78,  3, 48],
        [39, 45, 89, 73]],

       [[20, 51,  4,  4],
        [72, 52, 38, 23],
        [57, 18, 39, 96],
        [46,  4, 39, 67],
        [30, 41,  7, 55]],

       [[42, 22, 93, 47],
        [57, 53, 94,  6],
        [ 6, 62, 96, 68],
        [68, 88, 55, 94],
        [48, 94,  6, 55]]])

In [63]:
display(arr3,arr3.T)

array([[[55, 20, 42],
        [ 5, 72, 57],
        [72, 57,  6],
        [66, 46, 68],
        [39, 30, 48]],

       [[67, 51, 22],
        [73, 52, 53],
        [44, 18, 62],
        [78,  4, 88],
        [45, 41, 94]],

       [[77,  4, 93],
        [10, 38, 94],
        [19, 39, 96],
        [ 3, 39, 55],
        [89,  7,  6]],

       [[86,  4, 47],
        [58, 23,  6],
        [47, 96, 68],
        [48, 67, 94],
        [73, 55, 55]]])

array([[[55, 67, 77, 86],
        [ 5, 73, 10, 58],
        [72, 44, 19, 47],
        [66, 78,  3, 48],
        [39, 45, 89, 73]],

       [[20, 51,  4,  4],
        [72, 52, 38, 23],
        [57, 18, 39, 96],
        [46,  4, 39, 67],
        [30, 41,  7, 55]],

       [[42, 22, 93, 47],
        [57, 53, 94,  6],
        [ 6, 62, 96, 68],
        [68, 88, 55, 94],
        [48, 94,  6, 55]]])

In [65]:
display(arr3.shape,arr3.T.shape)
# 其实第三维和第一维进行了转置，互换

(4, 5, 3)

(3, 5, 4)

In [67]:
import numpy as np

In [69]:
np.transpose(arr3,axes = [2,1,0])
# transpose -  变换转置的意思 - 其实就是上面的 .T

array([[[55, 67, 77, 86],
        [ 5, 73, 10, 58],
        [72, 44, 19, 47],
        [66, 78,  3, 48],
        [39, 45, 89, 73]],

       [[20, 51,  4,  4],
        [72, 52, 38, 23],
        [57, 18, 39, 96],
        [46,  4, 39, 67],
        [30, 41,  7, 55]],

       [[42, 22, 93, 47],
        [57, 53, 94,  6],
        [ 6, 62, 96, 68],
        [68, 88, 55, 94],
        [48, 94,  6, 55]]])

#### 堆叠

In [70]:
arr4 = arr1[::7] #每隔7个取1个
arr4

array([99, 65, 54,  8, 37, 79, 49, 63, 74])

In [73]:
arr5 = arr1[::8]
arr5

array([99, 74, 52, 55, 19, 48, 15, 74])

In [74]:
np.concatenate([arr4,arr4,arr4,arr5])
#也能 执行合并
#级联，数据增长

array([99, 65, 54,  8, 37, 79, 49, 63, 74, 99, 65, 54,  8, 37, 79, 49, 63,
       74, 99, 65, 54,  8, 37, 79, 49, 63, 74, 99, 74, 52, 55, 19, 48, 15,
       74])

In [79]:
arr1 = np.random.randint(0,10, size = (5,3))
arr2 = np.random.randint(0,10, size = (2,3))
arr3 = np.random.randint(0,10, size = (5,2))
arr4 = np.random.randint(0,10, size = (2,4))
display(arr1,arr2,arr3,arr4)
# 不对应是没法合并的，比如 arr1和arr4
# 数据维度不合

array([[4, 8, 9],
       [8, 7, 5],
       [8, 0, 2],
       [5, 3, 9],
       [3, 6, 7]])

array([[1, 0, 1],
       [6, 9, 5]])

array([[8, 5],
       [0, 4],
       [8, 1],
       [2, 6],
       [8, 2]])

array([[6, 1, 4, 3],
       [9, 1, 8, 4]])

In [78]:
np.concatenate([arr1,arr2],axis = 0)# 0表示 第一维合并
# 也是可以级联的

array([[3, 2, 3],
       [7, 3, 2],
       [5, 0, 9],
       [6, 9, 4],
       [3, 5, 5],
       [9, 3, 1],
       [2, 1, 9]])

In [80]:
np.concatenate([arr1,arr3],axis = 1)# -1写成 1都是一回事
#数据在第二个维度上，进行了合并。

array([[4, 8, 9, 8, 5],
       [8, 7, 5, 0, 4],
       [8, 0, 2, 8, 1],
       [5, 3, 9, 2, 6],
       [3, 6, 7, 8, 2]])

In [81]:
display(arr1.shape,arr3.shape)
# 其实就是第二维 3+2=5

(5, 3)

(5, 2)