# 1.基本操作

## 1.1 创建

In [3]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [5]:
arr2 = np.random.randint(0,100,size = (10))
arr2

array([49, 38, 30, 73, 93, 44, 90, 39, 25, 78])

In [7]:
arr3 = np.random.randn(10)#正态分布
arr3
#平均值为0，标准差为1

array([ 0.82466936,  1.8396129 ,  0.8580169 ,  0.99843934,  0.4628025 ,
        0.77621011,  1.84809321, -1.7707937 , -1.26174477, -0.37582213])

In [8]:
# 以上创建的都是一维数组

In [9]:
np.random.randint(-50,50,size = (5,3))
#生成了一个5行3列， size 就是数量

array([[ -2,  24,  -2],
       [  5,  49,  40],
       [-25, -32,  43],
       [ -1, -21,  10],
       [ -2,  -2, -25]])

In [10]:
np.ones(shape = (5,3))
# ones生成的所有数据都是1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.zeros_like(arr3)
#传一个参数，a就是一个
#创建了10个都是0的数据。

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
# 等差数列
arr1 = np.arange(0,10,3)
arr1

array([0, 3, 6, 9])

In [14]:
np.linspace(1,99,50)# 1-99 分成50份，刚刚好，1，3，5，7，
#这也是一个等差数列

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
       79., 81., 83., 85., 87., 89., 91., 93., 95., 97., 99.])

In [18]:
np.set_printoptions(suppress=True)

In [20]:
# 等比数列
np.logspace(1,10,num = 10,base = 2)
#加上上面那个之后就不显示科学计数法了。
#显示就变成了数字
#如何改成整数呢，把那个0改成1. 0,10,num,的0改成1
#得到了一个等比数列

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

#### 查看操作

In [23]:
arr = np.random.randint(0,100,size = (20,16,5))
arr
#这是一个三维数组，三个中括号那么就是三维的

array([[[69, 51, 33, 36, 28],
        [48,  3, 32, 79, 86],
        [15, 23, 20, 23, 77],
        ...,
        [87, 81, 89,  6,  5],
        [60, 30,  9, 61,  0],
        [54, 67, 15, 10, 64]],

       [[79, 10, 98, 87, 13],
        [19,  4, 39, 71, 73],
        [32,  0, 40, 55, 16],
        ...,
        [51, 60, 32, 53, 84],
        [47, 39, 75, 25, 26],
        [59, 27, 38, 24, 27]],

       [[20, 23,  6, 27,  7],
        [97, 84,  0, 63, 99],
        [12, 76, 34,  8, 72],
        ...,
        [57,  5, 46, 14,  4],
        [50, 65, 56, 86,  2],
        [89, 40, 24, 59, 13]],

       ...,

       [[73, 74, 92, 65, 75],
        [ 4, 62,  9, 12, 66],
        [41, 72, 66, 22, 32],
        ...,
        [81, 80, 76, 73, 59],
        [40, 51, 73, 95,  4],
        [44, 68, 42, 63,  3]],

       [[ 6, 44, 80, 67, 35],
        [ 3, 61, 14, 78, 57],
        [68, 55, 91, 52,  5],
        ...,
        [37, 24, 16, 80, 72],
        [45, 50,  4, 18, 90],
        [98, 10, 60, 87, 33]],

       [[70,

In [24]:
arr.shape
#如上所说，如果遇到一个特别大的数组，不知道它的类型，
#那么就可以， arr.shape 就能查看到它的一个数组数据
# 20 行，16列，每行的数是5，每一行每一列的数据交叉点是5个

(20, 16, 5)

In [27]:
arr = np.random.randint(0,100,size = (2,6,5))
arr
# 中间那个6虽然指的是6列，但是其实相当于6行
# 5的话每一行5个数
#三维就可以看 arr.shape就可以了，看形状就可以了

array([[[79, 35, 23, 70, 34],
        [ 5, 53, 95,  4, 47],
        [83, 85, 56, 76,  4],
        [44, 55, 55,  3, 43],
        [15, 54, 76, 24, 40],
        [29, 30, 18, 91, 49]],

       [[ 2, 90, 15, 60, 95],
        [20, 65, 57,  9, 14],
        [44, 65, 37, 39, 14],
        [49, 82, 46, 82, 36],
        [18, 83, 85, 18, 68],
        [15, 55, 63, 80, 41]]])

In [29]:
arr = np.random.randint(0,100,size = (5,6))
arr

array([[19, 87, 31, 14,  8, 25],
       [81, 49, 76, 15, 84, 65],
       [66, 46, 25,  0, 15, 69],
       [69, 72, 67,  5, 39, 70],
       [39, 56, 72, 26, 64, 71]])

In [30]:
arr = np.random.randint(0,100,size = (3,5,6,8))
arr
#比如说四维数组，都是一样的

array([[[[13, 23, 74, 89, 50, 13, 13, 46],
         [78, 85, 21, 28, 78, 62, 41, 46],
         [40, 72,  9, 87, 25, 67, 12, 37],
         [82, 77, 43, 61, 62, 53, 87, 99],
         [98, 47, 69, 97, 96, 62, 12, 22],
         [76, 18, 23,  6, 44, 78, 16, 77]],

        [[30,  5, 31, 25, 31,  5, 15, 47],
         [29,  0, 81, 10, 95, 36, 82,  2],
         [26, 57,  3, 18,  1, 93, 88, 69],
         [35, 67, 36, 79, 82, 65, 99, 68],
         [53,  7, 51, 79,  6, 70, 49,  4],
         [28, 24, 47, 99,  7, 97, 84,  3]],

        [[39, 41, 34, 56, 68, 65, 24, 66],
         [70, 16, 97, 11, 14, 65, 16, 51],
         [73, 19, 52, 36, 96,  5, 71, 50],
         [62, 18, 53, 46, 10, 15, 71, 64],
         [81, 34, 33,  6, 27, 29, 48, 28],
         [36,  7,  7, 65, 25, 92, 24, 60]],

        [[77, 65,  8, 31, 20, 21, 18, 22],
         [24, 20, 25, 98, 33, 60, 45, 23],
         [53, 80, 94, 11, 85, 71, 15, 25],
         [59, 58, 51, 55, 97, 91, 95, 17],
         [ 5, 48, 77, 33, 70, 70, 79, 75],
     

In [31]:
arr.shape

(3, 5, 6, 8)

In [32]:
# 查看数据类型
arr.dtype

dtype('int32')

In [33]:
arr.size
# 一共多少个数，720.

720

In [34]:
3*5*6*8
#为什么 720？  3*5*6*8

720

In [35]:
#也可以查看数据的维度
arr.ndim

4

#### 文件操作

In [36]:
# IO操作

In [37]:
arr1 = np.random.random(size = (3,5))
arr1

array([[0.58435914, 0.51241512, 0.39947009, 0.29806727, 0.77606518],
       [0.00979123, 0.18822382, 0.08123241, 0.33952356, 0.69973228],
       [0.27757281, 0.09857063, 0.54564505, 0.60803822, 0.56562629]])

In [38]:
np.save('./arr1',arr1)
#文件后缀，默认是npz。
#此时返回的话，会出现一个  arr1.npy的文件。就会直接保存了。

In [39]:
#如果要声明的话，可以这样写
np.save(file = './arr1',arr = arr1)
#要同时声明，如果一个声明，一个不声明，就会报错
#np.save(file = './arr1',arr1)  ,比如这样

In [40]:
#  但是保存的那个 arr1.npy虽然打不开，但是我们可以读取
np.load('./arr1.npy')
#就会出现

array([[0.58435914, 0.51241512, 0.39947009, 0.29806727, 0.77606518],
       [0.00979123, 0.18822382, 0.08123241, 0.33952356, 0.69973228],
       [0.27757281, 0.09857063, 0.54564505, 0.60803822, 0.56562629]])

In [41]:
arr2 = np.logspace(1,10,num = 10,base = 2)#创建等比数列
arr2

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [42]:
np.savez('./file2',arr_x = arr1,arr_y = arr2)

In [43]:
np.load('./file2.npz')['arr_x']
#加载 np.load

array([[0.58435914, 0.51241512, 0.39947009, 0.29806727, 0.77606518],
       [0.00979123, 0.18822382, 0.08123241, 0.33952356, 0.69973228],
       [0.27757281, 0.09857063, 0.54564505, 0.60803822, 0.56562629]])

In [44]:
np.load('./file2.npz')['arr_y']

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [48]:
np.savetxt('./arr1.txt',arr1,delimiter = ',',fmt = '%.5f')# 加f标识float，加e表示科学计数法
# 表示浮点数，e代表科学计数法
#保存成txt 文件

In [51]:
np.savetxt('./arr1.csv',arr1,delimiter = ':',fmt = '%.5f')
# 这个文件和上面txt 间隔有差异，
# 一个是分号，一个是逗号。

# csv这个数据可以自动生成 Excl的数据

In [52]:
np.savetxt('./arr2.csv',arr1,delimiter = ',',fmt = '%.5f')

# 两个区别在于 上面那个是 用 : 号隔开， 下面用的是 ,号隔开。