In [1]:
print(123)

123


print(123)

### 브로드캐스트 메커니즘 

#### 1차원 배열 브로드캐스트

In [3]:
[0,1,2,3] * 3

[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]

In [9]:
import numpy as np
# sort 정렬
# [0,1,2,3]*3
arr1 = np.sort(np.array([0,1,2,3]*3)).reshape(4,3) #shape(4,3)
display(arr1)
arr2 = np.array([1,2,3]) # shape(3,)
display(arr2)
arr3 = arr1 + arr2 # arr2를 복사하여 4번 브로드캐스트합니다. shape(4,3)
arr3 # jupyter는 변수를 출력합니다. 【Pycharm은 해당 작업이 없습니다.】 

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

array([1, 2, 3])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [5]:
display(arr2)

array([1, 2, 3])

#### 2차원 배열 브로드캐스트

In [13]:
import numpy as np
arr1 = np.sort(np.array([0,1,2,3]*3)).reshape(4,3) # shape(4,3)
# arr2，이차원
arr2 = np.array([[1],[2],[3],[4]]) # shape(4,1)
display(arr1,arr2)
arr3 = arr1 + arr2 # arr2 进行广播复制3份 shape(4,3)
display(arr1,arr2,arr3)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

array([[1],
       [2],
       [3],
       [4]])

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

array([[1],
       [2],
       [3],
       [4]])

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])

#### 고차원 배열 브로드캐스트

In [3]:
import numpy as np
arr1 = np.array([0,1,2,3,4,5,6,7]*3).reshape(3,4,2) #shape(3,4,2)
# arr2 = np.array([0,1,2,3,4,5,6,7]).reshape(4,2) #shape(4,2)
# arr2 = np.random.randint(0,10,size = (3,4,1))
arr2 = np.random.randint(0,10,size = (3,1,2))
display(arr1.shape,arr2,arr2.shape)
arr3 = arr1 + arr2 # arr2 배열의 0차원을 기준으로 3번 복사합니다. shape(3,4,2)
arr3


(3, 4, 2)

array([[[0, 3]],

       [[4, 0]],

       [[4, 8]]])

(3, 1, 2)

array([[[ 0,  4],
        [ 2,  6],
        [ 4,  8],
        [ 6, 10]],

       [[ 4,  1],
        [ 6,  3],
        [ 8,  5],
        [10,  7]],

       [[ 4,  9],
        [ 6, 11],
        [ 8, 13],
        [10, 15]]])

### 일반 함수

#### 원소 수치 함수

abs、sqrt、square、exp、log、sin、cos、tan，maxinmum、minimum、all、any、inner、clip、round、trace、ceil、floor

In [27]:
import numpy as np
arr1 = np.array([1,4,8,9,16,25])
print(np.sqrt(arr1)) # 제곱근
print(np.square(arr1)) # 제곱
print(np.clip(arr1,2,16)) # array([ 2,  4,  8,  9, 16, 16])

[1.         2.         2.82842712 3.         4.         5.        ]
[  1  16  64  81 256 625]
[ 2  4  8  9 16 16]


In [28]:
# 자연상수를 밑으로 하는 지수 함수
np.exp(np.array([1,2,3]))

array([ 2.71828183,  7.3890561 , 20.08553692])

In [31]:
np.e**3

20.085536923187664

In [32]:
x = np.array([1,5,2,9,3,6,8])
y = np.array([2,4,3,7,1,9,0])
print(np.maximum(x,y)) # 두 배열 중 큰 값 반환

[2 5 3 9 3 9 8]


In [33]:
arr2 = np.random.randint(0,10,size = (5,5))
np.inner(arr2[0],arr2) #1차원 배열 벡터 내적 반환

array([ 99, 109, 138,  68,  55])

In [35]:
display(arr2,arr2[0])

array([[1, 6, 2, 7, 3],
       [9, 5, 2, 9, 1],
       [8, 8, 5, 9, 3],
       [8, 2, 5, 2, 8],
       [3, 0, 1, 5, 5]])

array([1, 6, 2, 7, 3])

In [39]:
for i in range(5):
    print((arr2[0] * arr2[i]).sum())

99
109
138
68
55


#### where 함수 사용


In [42]:
import numpy as np
arr1 = np.array([1,3,5,7,9])
arr2 = np.array([2,4,6,8,10])
cond = np.array([True,False,True,True,False])
np.where(cond,arr1,arr2) # True - arr1，False - arr2값
#  array([ 1,  4,  5,  7, 10])

array([ 1,  4,  5,  7, 10])

In [43]:
arr3 = np.random.randint(0,30,size = 20)
display(arr3)
np.where(arr3 < 15,arr3,-15) # 15보다 작으면 자기 자신의 값으로 유지하고, 15보다 크면 -15로 설정합니다 

array([ 9,  0,  6, 15, 26,  1, 28, 23, 19, 21, 25, 20, 27,  0, 27, 19, 15,
       12,  0, 24])

array([  9,   0,   6, -15, -15,   1, -15, -15, -15, -15, -15, -15, -15,
         0, -15, -15, -15,  12,   0, -15])

#### 정렬 방법

In [46]:
import numpy as np
arr = np.array([9,3,11,6,17,5,4,15,1])
display(arr)
arr.sort() # 원래의 배열을 직접 수정합니다.
arr

array([ 9,  3, 11,  6, 17,  5,  4, 15,  1])

array([ 1,  3,  4,  5,  6,  9, 11, 15, 17])

In [49]:
arr = np.array([9,3,11,6,17,5,4,15,1])
arr2 = np.sort(arr) # 깊은 복사본의 정렬 결과를 반환합니다.
arr2

array([ 1,  3,  4,  5,  6,  9, 11, 15, 17])

In [48]:
arr # 원래 데이터는 변경되지 않습니다

array([ 9,  3, 11,  6, 17,  5,  4, 15,  1])

In [51]:
arr = np.array([9,3,11,6,17,5,4,15,1])
index = arr.argsort() # 작은 값부터 큰 값 순으로 정렬된 인덱스를 반환합니다. (정렬 인덱스를 기반으로 나열합니다.)
# array([8, 1, 6, 5, 3, 0, 2, 7, 4])
display(arr,index)
# 인덱스를 기반으로 정렬합니다.
arr[index]

array([ 9,  3, 11,  6, 17,  5,  4, 15,  1])

array([8, 1, 6, 5, 3, 0, 2, 7, 4], dtype=int64)

array([ 1,  3,  4,  5,  6,  9, 11, 15, 17])

#### 집합 연산

In [52]:
A = np.array([2,4,6,8])
B = np.array([3,4,5,6])
print(np.intersect1d(A,B)) # 교집합 array([4, 6])
print(np.union1d(A,B)) # 합집합 array([2, 3, 4, 5, 6, 8])
print(np.setdiff1d(A,B)) #차집합，A에 있습니다，B에 없습니다 array([2, 8])


[4 6]
[2 3 4 5 6 8]
[2 8]


#### 수학 및 통계 함수

min、max、mean、median、sum、std、var、cumsum、cumprod、argmin、argmax、argwhere、cov、corrcoef

In [55]:
import numpy as np
arr1 = np.array([1,7,2,19,23,0,88,11,6,11])
print(arr1.min()) # 최솟값 계산 0
index = arr1.argmin()
arr1[index]

0


0

In [56]:
arr1.argmax() # 최댓값의 인덱스 계산 (6을 반환)

6

In [58]:
index = np.argwhere(arr1 > 20) # 20보다 큰 원소의 인덱스를 반환합니다
arr1[index]

array([[23],
       [88]])

In [59]:
np.cumsum(arr1) # 누적 합 계산

array([  1,   8,  10,  29,  52,  52, 140, 151, 157, 168])

In [61]:
arr2 = np.random.randint(0,10,size = (4,5))
display(arr2)
arr2.mean() # 열의 평균값 계산

array([[6, 4, 4, 1, 9],
       [1, 7, 2, 5, 1],
       [3, 2, 0, 3, 8],
       [4, 6, 1, 5, 2]])

3.7

In [63]:
arr2_mean = arr2.mean(axis = 0) # 이것이 행인지 열인지 계산합니다.
display(arr2_mean,arr2_mean.shape)

array([3.5 , 4.75, 1.75, 3.5 , 5.  ])

(5,)

In [64]:
arr2_mean = arr2.mean(axis = 1) # 이것이 행인지 열인지 계산합니다.
display(arr2_mean,arr2_mean.shape)

array([4.8, 3.2, 3.2, 3.6])

(4,)

In [65]:
np.var(arr2) # 분산 계산

6.210000000000001

In [68]:
((arr2 - arr2.mean())**2).mean()

6.210000000000001

In [73]:
arr2

array([[6, 4, 4, 1, 9],
       [1, 7, 2, 5, 1],
       [3, 2, 0, 3, 8],
       [4, 6, 1, 5, 2]])

In [72]:
np.cov(arr2,rowvar=True)

array([[ 8.7 , -5.2 ,  6.05, -2.85],
       [-5.2 ,  7.2 , -2.8 ,  4.35],
       [ 6.05, -2.8 ,  8.7 , -0.65],
       [-2.85,  4.35, -0.65,  4.3 ]])

In [81]:
np.cov(arr2[0],ddof=0) # 공분산 계산

array(6.96)

In [88]:
np.round(((arr2[0] - arr2[0].mean())**2),2).sum()/5 # 方差
# 분산에는 두 가지 계산 공식이 있습니다.

6.959999999999999

In [87]:
((arr2[0] - arr2[0].mean())**2).sum()/(5-1)

8.7

In [71]:
np.cov(arr2,rowvar=False) # 공분산 행렬 계산

array([[ 4.33333333, -1.83333333,  1.83333333, -3.        ,  5.66666667],
       [-1.83333333,  4.91666667,  0.91666667,  2.83333333, -8.        ],
       [ 1.83333333,  0.91666667,  2.91666667, -1.83333333,  1.66666667],
       [-3.        ,  2.83333333, -1.83333333,  3.66666667, -7.33333333],
       [ 5.66666667, -8.        ,  1.66666667, -7.33333333, 16.66666667]])

In [70]:
# 범위 -1부터 1까지
np.corrcoef(arr2,rowvar=True) # 상관계수 계산

array([[ 1.        , -0.6570183 ,  0.6954023 , -0.46596254],
       [-0.6570183 ,  1.        , -0.35377909,  0.78178761],
       [ 0.6954023 , -0.35377909,  1.        , -0.10627216],
       [-0.46596254,  0.78178761, -0.10627216,  1.        ]])

### 선형대수

In [89]:
#행렬 곱셈
A = np.array([[4,2,3],
              [1,3,1]]) # shape(2,3)
B = np.array([[2,7],
              [-5,-7],
              [9,3]]) # shape(3,2)
np.dot(A,B) # 행렬 연산에서 A의 마지막 차원과 B의 첫 번째 차원이 일치해야합니다.

array([[ 25,  23],
       [ -4, -11]])

In [90]:
A @ B # 기호 @는 행렬 곱셈 연산을 나타냅니다.

array([[ 25,  23],
       [ -4, -11]])

In [94]:
A = np.random.randint(0,10,size = (3,6))
B = np.random.randint(0,10,size = (6,7))
A.dot(B).shape

(3, 7)

In [97]:
np.set_printoptions(suppress=True)

In [102]:
#행렬의 역 계산
from numpy.linalg import inv,det,eig,qr,svd
A = np.array([[1,2,3],
              [2,3,4],
              [4,5,8]]) # shape(3,3)
B = inv(A) # 역 행렬
display(B)
display(A @ B)
det(A)#행렬의 행렬식 계산

array([[-2. ,  0.5,  0.5],
       [ 0. ,  2. , -1. ],
       [ 1. , -1.5,  0.5]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

-2.0000000000000004

### homework

In [107]:
import numpy as np

arr = np.random.randint(0,10,size = (2,3,4,5))
display(arr.shape)
# 
arr.sum(axis = (0,-1)).shape

(2, 3, 4, 5)

(3, 4)