### 정규 방정식

#### 이차 선형 방정식

$W = (X^TX)^{-1}X^Ty$

In [136]:
# 선형 회귀는 무엇인가요?
# 어떤 문제를 해결할 수 있나요?
import numpy as np
X = np.array([[1,1],[2,-1]])
y = np.array([14,10])

# 정규 방정식은 linalg 선형 대수를 사용합니다.
w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
w

array([8., 6.])

In [137]:
from sklearn.linear_model import LinearRegression # 선형 회귀

model = LinearRegression(fit_intercept=True) #  기본적으로 이 매개변수는 True이며, 일반적으로 True를 사용합니다.
model.fit(X,y) # 모델 구축, 훈련

# coef는 기울기, 선형 방정식, 계수 == 기울기, 절편
# 위의 방정식(변수, 계수, 기울기 + 절편을 구하는)에서 절편이 있나요?
display(model.coef_, model.intercept_)

array([-0.8,  1.6])

13.2

In [138]:
# # 절편 포함
# # x + y = 14
# -0.8 + 1.6 + 13.2 = 14

# # 2x - y = 10
# 2*-0.8 - 1.6 + 13.2 = 10

#### 8차원 일차 방정식

In [139]:
# 위의 8차원 일차 방정식에 해당하는 X 데이터와 대응하는 y 값은 다음과 같습니다:
X = np.array([[  0 ,14 , 8 ,  0 ,  5,  -2,   9,  -3],
 [ -4 , 10 ,  6 ,  4 ,-14 , -2 ,-14  , 8],
 [ -1 , -6  , 5 ,-12 ,  3 , -3 ,  2 , -2],
 [  5 , -2  , 3 , 10  , 5 , 11 ,  4  ,-8],
 [-15 ,-15  ,-8 ,-15 ,  7 , -4, -12 ,  2],
 [ 11 ,-10 , -2 ,  4  , 3 , -9 , -6 ,  7],
 [-14 ,  0 ,  4 , -3  , 5 , 10 , 13 ,  7],
 [ -3 , -7 , -2 , -8  , 0 , -6 , -5 , -9]])
y = np.array([ 339 ,-114  , 30 , 126, -395 , -87 , 422, -309])
display(X,y)

array([[  0,  14,   8,   0,   5,  -2,   9,  -3],
       [ -4,  10,   6,   4, -14,  -2, -14,   8],
       [ -1,  -6,   5, -12,   3,  -3,   2,  -2],
       [  5,  -2,   3,  10,   5,  11,   4,  -8],
       [-15, -15,  -8, -15,   7,  -4, -12,   2],
       [ 11, -10,  -2,   4,   3,  -9,  -6,   7],
       [-14,   0,   4,  -3,   5,  10,  13,   7],
       [ -3,  -7,  -2,  -8,   0,  -6,  -5,  -9]])

array([ 339, -114,   30,  126, -395,  -87,  422, -309])

In [140]:
# x1부터 x8까지는: 1., 5., 15., 3., 8., 4., 17., 12.
w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
w

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.])

In [141]:
model = LinearRegression(fit_intercept=False)
model.fit(X,y)
display(model.coef_,model.intercept_)

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.])

0.0

#### 8차원 일차 방정식 + 절편 [12]

In [142]:
y_new = y + 64
y_new

array([ 403,  -50,   94,  190, -331,  -23,  486, -245])

In [143]:
# 한 가지 고민할 문제는, 절편이 추가되면서 b, 미지수가 추가된다는 것입니다.
w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y_new)
w

array([-9.53423295, -3.18237714, 32.89293368, 13.94370726, 12.88345187,
       -5.64066992, 14.95379584,  8.62431708])

In [144]:
X_new = np.concatenate([X,np.ones(shape =(8,1))],axis = 1)
X_new

array([[  0.,  14.,   8.,   0.,   5.,  -2.,   9.,  -3.,   1.],
       [ -4.,  10.,   6.,   4., -14.,  -2., -14.,   8.,   1.],
       [ -1.,  -6.,   5., -12.,   3.,  -3.,   2.,  -2.,   1.],
       [  5.,  -2.,   3.,  10.,   5.,  11.,   4.,  -8.,   1.],
       [-15., -15.,  -8., -15.,   7.,  -4., -12.,   2.,   1.],
       [ 11., -10.,  -2.,   4.,   3.,  -9.,  -6.,   7.,   1.],
       [-14.,   0.,   4.,  -3.,   5.,  10.,  13.,   7.,   1.],
       [ -3.,  -7.,  -2.,  -8.,   0.,  -6.,  -5.,  -9.,   1.]])

In [145]:
X_new.shape

(8, 9)

In [146]:

w = np.linalg.inv(X_new.T.dot(X_new)).dot(X_new.T).dot(y_new)
w

array([ 31.7109375 ,  43.1328125 , -72.109375  ,  -8.6328125 ,
         6.4921875 ,  48.2265625 ,  12.44921875,  21.0546875 ,
       195.4375    ])

In [147]:
w = np.array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.])
b = 64
X9 = np.random.randint(-10,10,size = 8) # x1 ~ x8
y9 = w.dot(X9) + b # 따라서 9번째 방정식의 목표값을 얻을 수 있습니다.

# 데이터를 병합합니다
y_new = np.concatenate([y_new,[y9]])
y_new # 9

array([ 403.,  -50.,   94.,  190., -331.,  -23.,  486., -245.,  116.])

In [148]:
# 다시 돌립니다
X_new = np.concatenate([X_new,[np.concatenate([X9,[1]])]])
X_new

array([[  0.,  14.,   8.,   0.,   5.,  -2.,   9.,  -3.,   1.],
       [ -4.,  10.,   6.,   4., -14.,  -2., -14.,   8.,   1.],
       [ -1.,  -6.,   5., -12.,   3.,  -3.,   2.,  -2.,   1.],
       [  5.,  -2.,   3.,  10.,   5.,  11.,   4.,  -8.,   1.],
       [-15., -15.,  -8., -15.,   7.,  -4., -12.,   2.,   1.],
       [ 11., -10.,  -2.,   4.,   3.,  -9.,  -6.,   7.,   1.],
       [-14.,   0.,   4.,  -3.,   5.,  10.,  13.,   7.,   1.],
       [ -3.,  -7.,  -2.,  -8.,   0.,  -6.,  -5.,  -9.,   1.],
       [  9.,  -5.,  -4.,   3.,   1.,  -2.,   7.,   0.,   1.]])

In [149]:
model = LinearRegression(fit_intercept=False)

model.fit(X_new,y_new)
display(model.coef_,model.intercept_)

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12., 64.])

0.0

In [150]:
model = LinearRegression(fit_intercept=True)

model.fit(X_new,y_new)
display(model.coef_,model.intercept_)

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.,  0.])

63.99999999999997

In [151]:

w = np.linalg.inv(X_new.T.dot(X_new)).dot(X_new.T).dot(y_new)
w

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12., 64.])

$（X^TX)^{-1}X^TY$

$X^{-1}Y$

In [152]:
X

array([[  0,  14,   8,   0,   5,  -2,   9,  -3],
       [ -4,  10,   6,   4, -14,  -2, -14,   8],
       [ -1,  -6,   5, -12,   3,  -3,   2,  -2],
       [  5,  -2,   3,  10,   5,  11,   4,  -8],
       [-15, -15,  -8, -15,   7,  -4, -12,   2],
       [ 11, -10,  -2,   4,   3,  -9,  -6,   7],
       [-14,   0,   4,  -3,   5,  10,  13,   7],
       [ -3,  -7,  -2,  -8,   0,  -6,  -5,  -9]])

In [153]:
X.T

array([[  0,  -4,  -1,   5, -15,  11, -14,  -3],
       [ 14,  10,  -6,  -2, -15, -10,   0,  -7],
       [  8,   6,   5,   3,  -8,  -2,   4,  -2],
       [  0,   4, -12,  10, -15,   4,  -3,  -8],
       [  5, -14,   3,   5,   7,   3,   5,   0],
       [ -2,  -2,  -3,  11,  -4,  -9,  10,  -6],
       [  9, -14,   2,   4, -12,  -6,  13,  -5],
       [ -3,   8,  -2,  -8,   2,   7,   7,  -9]])

### 정규 방정식 유도입니다.

In [158]:
theta = np.random.randint(0,10,size = 8)
theta

array([2, 5, 4, 8, 0, 3, 7, 0])

In [160]:
X = np.random.randint(0,10,size = 8)
X

array([4, 1, 3, 9, 5, 4, 6, 2])

In [161]:
y = X.dot(theta)
y

151

In [162]:
theta.dot(X)

151